apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: fastcgi
      protocol: TCP
      name: fastcgi
  selector:
    {{- include "laravel.selectorLabels" . | nindent 4 }}
